#!/bin/sh
# Generate MunkiReport .env from container environment variables.
# Docker passes these via the environment: block in docker-compose.yml;
# this script writes them into the file the PHP app actually reads.

ENV_FILE="/var/munkireport/.env"

cat > "$ENV_FILE" <<EOF
SITENAME=${SITENAME}
WEBHOST=${WEBHOST}
PASSPHRASE=${PASSPHRASE}

CONNECTION_DRIVER=${CONNECTION_DRIVER}
CONNECTION_HOST=${CONNECTION_HOST}
CONNECTION_PORT=${CONNECTION_PORT}
CONNECTION_DATABASE=${CONNECTION_DATABASE}
CONNECTION_USERNAME=${CONNECTION_USERNAME}
CONNECTION_PASSWORD=${CONNECTION_PASSWORD}
CONNECTION_CHARSET=${CONNECTION_CHARSET}
CONNECTION_COLLATION=${CONNECTION_COLLATION}

AUTH_METHODS=${AUTH_METHODS}
ROLES_ADMIN=${ROLES_ADMIN}
ALLOW_MIGRATIONS=${ALLOW_MIGRATIONS}

MODULES=${MODULES}
EOF

chown www-data:www-data "$ENV_FILE"
chmod 600 "$ENV_FILE"

exec apache2ctl -D FOREGROUND
